apiVersion: v1
kind: Secret
metadata:
    name: s3-advisor-corpus
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: advisor
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: advisor
type: Opaque
stringData:
    ADVISOR_CORPUS_S3_ACCESS_KEY: ENC[AES256_GCM,data:2DjYTq1Vb3R+F7t3JozQ1rfIN9huiYDL,iv:aNVuD5jnfcZhkGihGG3uVshei9rFuhBkywG3f5fiLmk=,tag:yKLOWKXZib7Au5rB5T7bPg==,type:str]
    ADVISOR_CORPUS_S3_SECRET_KEY: ENC[AES256_GCM,data:C/4rvDqfTAKSge31tHWmwAtWsM/JQAXGskQwLPbFY9VMNbkayEmyKnPaD97SsLe5peVfyGoYvbJIpd1xxA5wfQ==,iv:zASoGUPwCw35e+MjfBe4ZT38R4hU1OJoZwCUEfUuMbc=,tag:2wI3aJOkdgyUpsY6/z24+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNU2Z1Uk0xM240RlR3OUxC
            TUZMbC9wS1kyM2JSeUtvWnIrWk1iTFFGV1M4Clk5WVRXYmlkdzRscUNCS015eEc4
            dmhsYlZ2OGl0TGN3cUx6dnlsRTBoSVkKLS0tIGhaUkV3dG5OVTVRSjg4eXd3UDNa
            V3hFT3ZtTDBwZHJVdi9hbjU0ODM3VTQKgS+3iZnthOMrrB82IgdTAsOutNuBtLah
            jjiqezfBMgGpUd7PgvGGMC+a3zwNUICYHL9S/+aigRlB2ha4GyiMhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T01:30:22Z"
    mac: ENC[AES256_GCM,data:Ioo5yTqDBvU6/oqNhz6RfMmJbJDxXyCUIUT5CAMH+jI7RUQ80MzVZmwycq1guHmKsl45StiByQ3CHuFigbuCMR8B1tfxBUj8pXhbFjGA0G98zPYO4AkOcw1BGcU4dp5D1PJ3+9LQt4Pibn6UFyPwjExrv7tD9gmhS0549Dorb3g=,iv:/Kz/EbZKcIbA9/Ia6Wat54pGG/14vkQztiV8HHi7wBA=,tag:7y2vLRuJD/Gh19xSSnJRUg==,type:str]
    version: 3.13.3
