apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-tls
  namespace: registry
spec:
  secretName: registry-tls
  dnsNames:
    - registry.eliorion.fr
  # Prod rate limit: 5 duplicate certs/week. Test dnsNames changes on letsencrypt-staging first.
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
