apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ai-gateway-db
  namespace: ai-gateway
spec:
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: garage-store
        serverName: ai-gateway-db
