apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperclip-db
spec:
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: garage-store
        serverName: paperclip-db
