apiVersion: v1
kind: Secret
metadata:
    name: nao-ai-gateway-token
    namespace: database
type: Opaque
stringData:
    AI_GATEWAY_TOKEN: ENC[AES256_GCM,data:P6bJ36B2Ydb5EQ==,iv:4+9OTOO0a61SWUUyNVC0w6peLoGAwy5ydg5qcibhyqU=,tag:4S9HEiuA/YJlPnDWa8UcGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNmN6MEhLcmFVUmJsellL
            OHhmSHRWR1dRSWtiWWtoMTVVZTR6Z3ZqelhJCmpmUFgwTGVVWFV6NTl5YXBSLzIx
            QWw3SjhldGZWS2UyWWc0ZFVkRXVHNEkKLS0tIFNkRDVnSWlIODd5ZEtHclFQelhV
            bFFVNTRmanBLY3FpMUNyZXRKTE8zMWsKuWKHXnkWm8Gc/ggEmhHm3faEe+adhsYS
            6STznCe5iPDKbFaTietcFajV8h4htEbkSLhdBMlG55XsffTqV99I+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T08:30:53Z"
    mac: ENC[AES256_GCM,data:3FDOwm1C0BApMS1lxgf14arFcfWH1HDK8uRVbRSx2fbkX3K0hNhiZ9EpTF9E2bar1hmw1lYfKFjmgjIf72TYNcqrzjjYt9ip+vd/8u27VMt42f6Dji8Q/a3lRLMOkliQ9BY6nbc2tmsOLFIkuwtahWzW6myMwW0KXgaBpZ1nP8I=,iv:Y6xfK2PAfFXvfLKmRZvtkpvyeM07H3GwZj5Rht+5JY4=,tag:O2ymxUbdSFuwc+3Qlfga6Q==,type:str]
    version: 3.13.3
