apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - job.yaml
configMapGenerator:
  - name: openbao-config
    namespace: openbao
    files:
      - configure.sh
      - eso-policy.hcl
      - eso-namespaces.txt
