apiVersion: v1
kind: Secret
metadata:
    name: fbref-mcp-ro
    namespace: fbref
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Chb+IALv,iv:HsvvCXAK85kJC8mFnRtfQrSC42zx5my68LF+15QJ37I=,tag:I5nAOG0DDGQhinBR/TNfDA==,type:str]
    password: ENC[AES256_GCM,data:Q5yfKjIvScCcw4AAuGVC2aqClKvtkV/PerQFWGmSOCMk17ImZ0MtD+73Lw==,iv:eALvbXevHy2KXh7mqQ/uPJg5/WLVqu+CDS1qgHQ2heM=,tag:ioNbrOLuogSSz8mu1AedOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQWttTEpMZ1R0Mk91RmdF
            Ykt4Tjc2b2h3UnJHays1Sm5iWmlRQlpONW13CjM3c1VYR3JjYVZBOVpnclFvT01G
            Y3VNdlBqN0Q5SVNLcFlFWi9Henc1ZmcKLS0tIEpDaUl6dGR3WHNmUS9sb1BzV2F1
            TXdvR1lDY2pXbmhOYTlpQmU1VWRaZ2cKlWAGL+r517YRPZ0D4owf+EAKJehljOxt
            JIx1K8CRRBUpnvlsq4vmtmXJdHQiLlDQIaBH7S7Cjg6btm05jxGvQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T14:44:53Z"
    mac: ENC[AES256_GCM,data:5pbU3tmlRZ3rMUsI9FZoNdqmeAs4AXPUf+rgZBPBaolDlDa4okuBzJt2zS4IWj52PF7g0CFXMNlSSkbDhYP9SEBI1dsw43H6sADqAxg7HX26XV3g5UodIDoO/tHAByRvmaFCgeiIlU7rnA0O8LCM3Q1IhjCLn2K2GuELd9ABq+0=,iv:Eb0Mt8klFJynXltRYg8mx05tiPrRdr7uaORfARlluNo=,tag:OXDllZVQaw+a8dhg/Xih7g==,type:str]
    version: 3.13.3
