apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scraper

resources:
  - ../../../base/databases/scraper

patches:
  # PVCs on Longhorn.
  - path: cluster-storage-patch.yaml
    target:
      kind: Cluster
      name: scraper-db
  # Permit reflection of the -app secret into the `database` ns.
  - path: cluster-reflector-patch.yaml
    target:
      kind: Cluster
      name: scraper-db
