apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperclip

resources:
  - ../../base/paperclip
  - configmap.yaml
  - paperclip-auth.enc.yaml
  - paperclip-claude.enc.yaml
