apiVersion: v1
kind: Secret
metadata:
    name: paperclip-claude
    namespace: paperclip
type: Opaque
stringData:
    CLAUDE_CODE_OAUTH_TOKEN: ENC[AES256_GCM,data:bSYtQxli5v42BhVFTLYIX+J2/pXQk4mesH/d7obnWQ==,iv:IhudRRtoxequwQ7dfFfUvdiMYYD9K2LHeCtiWtVFEFo=,tag:3JuZvOSe3//hIBa0/I/YaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxU3hDdlphZUlqYjFRT1JT
            UXlMQXh4WUI4V3lCMmNiV0M5SUphMkx5QkcwCkdveVJUdVptbWJLNnlKemwzRlRl
            WmlhWTFHaDVNc1ovR0NpZFp4OU1ZR2sKLS0tIGlxemVUQlNQdy9mWEJFTFdGODdz
            bHg3TjlCOG1BeEcvTGZPdmhFKys3eTgKDWMM8+R/y1LYu+kApO6tfsJw7wBtTagG
            zc8V8DgiuHqVziWN4S9QGY0yrGaKh9iyTlo+Z/V6DmqWdZcTXusNAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T03:26:33Z"
    mac: ENC[AES256_GCM,data:q3JGhPvYnJIAwVXm6J9AXkPzLJMipteAWVcYeQpy9FkNov83N+jkp5RPEFG8tA4N4PoiFx5Upw9fvrEulRGqzf832A3mZ6IOsW4n067JO2F/f+6sCsELyd8G54CmpuK/g4Jqv1CfrTLJrRHC1DxjeVFQukvlMnYvVMQrsR9fY/4=,iv:I2mS03rNicJWfSfkMFsaPCBlNEYWekknr8FXJzr6gJA=,tag:HAnnCuub+JfV3iiyGMhVHQ==,type:str]
    version: 3.13.3
