apiVersion: v1
kind: Secret
metadata:
    name: paperclip-secrets-key
    namespace: paperclip
type: Opaque
stringData:
    PAPERCLIP_SECRETS_MASTER_KEY: ENC[AES256_GCM,data:uwRb5zoYn1+9XRtbNnheFXYH7mM13A71TuGSVaN5oH+PYx87FAD8zekW/5eaCQ1/PUMK8iJwm8IcOUtdkYyEUA==,iv:FM4oR/MYvgZYFzcgsiDIqcGGGXofVs+QuETXIHVR3gI=,tag:gv26UHHxlXWrGQdMPkeUXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUWtNdGpjZlBia2p4UTlP
            M1RPL3F2bE95aldUWUJTUUlzOGdkajQ2MWd3ClFRMU1NWEdUUWxuQW1nb3F5UXU4
            OWNCeERNM25pNElYQlA2N20zdFhtK1kKLS0tIGVMbUZiOG1rNXZuVVZjcHBVUUw0
            WkRyYnN0RXQxSTd1VmNOKzhPWDBEOFkK38eLEPCn1m0uAAGSz3E5V9wxqlZY1qGG
            e0pYmseOYgtX0U4dgGNtkc4fhqOaNyx9K3QdxjNO/OMg9NSGfN0Ggg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T23:47:32Z"
    mac: ENC[AES256_GCM,data:8Ytcu/4AYXKezxEJ7A0j6ciyJsmGYffg4BUCAwYZSXUQB9+t84iK1e7M4tSqAZclIZ8uWSF+4vtXqd55I/GeaTkxF5s+/HrYxZ61Ag8MH6/3gJSOslTdeY05jSpdupmcEDCTsB/ANaIc+GYIEZmOhHuUj7e+zWoi8RK3bVobQOM=,iv:D1+2lq8oF4jTjNBiu2wpBISutlN25cM5bCFIJL5Solw=,tag:mh3lwbteRaoUF6zPmZLmKQ==,type:str]
    version: 3.13.3
