apiVersion: v1
kind: Secret
metadata:
    name: paperclip-github
    namespace: paperclip
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:GT7gHMfWVtsiWxxfgGfAQrYA5yv+Ibouc7U7CDsZqNz3DEeKjHCOXWCXVjoTE5uGBJMfHzTHEgMSvNeVcjG9EmV8Gg8vCJEUQYOlPjbuxvUscQtWtrmRvs4s4HcP,iv:5RlVl2jEAVTpxsEKJ5gSIVN40AHX377kbJwz5/YhfSI=,tag:3iiWi2id2kyiVSNXUboklg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWVJyc0UvNEFURzhpcTJV
            aytHUkFLTGdHcEd2bVAwYThtYUdjTTlzUXdRClZNK1lOSHYydzZNTm04ZmppRmJW
            cDU2ODZnY09BMDg2dVhUczBmaGZMOGsKLS0tIDZKNUU0QjlpQnU0d2gwOGd4SkZu
            cUJsY3BBUFc3SDh6SWE3MEpsSVE3ZTAKnVyxPlDtix+Rgpj1BEe4d+cN3VOvRfwv
            pLs4Lw1v1sqlxlegntnIlEjntNfDsfvngBCS10jmN6z/7ecTxEcdxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T04:08:42Z"
    mac: ENC[AES256_GCM,data:dKbVc/whl9d74x+p4j61OWBn9ljNjn4OMIAvVgRpE6vy4bjbem6FSNMHJTKaf95lTpY+upfKuphNggk5lw89dNzy+gjuODEk3VK0waEcnKz8nvdnZlVPwX1Tnm90UCKR9Uu7HCovHZM/M01BSOpsbZ/n7VZ1TxZsA3s0YRMgIdk=,iv:OnpyOotyCt1iugw7CV1VcY6Oox6O0u24dEzavr9Hw+M=,tag:BM0KYL9uHyh9vcvzZDS3QA==,type:str]
    version: 3.13.3
