apiVersion: v1
kind: Secret
metadata:
    name: paperclip-secrets
    namespace: paperclip
type: Opaque
stringData:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:7KfCIxyUWJPb5YxQF1EUReD4Mj2fC2oySiA4Q0NQy5y4DnQWVe26fd6oHXAYkAlr/UnPgctB6KoFg5W8YIyq1Q==,iv:lwhgwKnrqiSM8CO4BeorCmXrl4myQnVzWcOUojT+Ed4=,tag:Ifj5D/7siA58NJpCUx3qyw==,type:str]
    CLAUDE_CODE_OAUTH_TOKEN: ENC[AES256_GCM,data:6LIZRlJZI+mKhJNihChJWQA6IHc=,iv:AaAx8EJhPcVCP5s/3CPyHTeBEqWBOjWdMufFjt9vHhs=,tag:bNybt41GvtzEh8SizUj95w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVN2FhMUUvSDBIZ05GY1J4
            QmcwTkswVGhXRzlaNnIxTmk2RjkxT0RablNFCmxFbGZkNmJtTGxMS0o3MEJ6UzQz
            Lytucy9rbVdseFF0MFlYc0FjU3R4TFUKLS0tIFNOZmZTbzVjZ1JmYS9FQmlKV015
            QUVuV2NWckR0VHpqL3dvNXFUV1B1dmsK632qwkUaR8w2pwSME9tu4NwQXZpi9fDU
            xV1ith1MmklMY0lhJOk/69ATw9FUoRX5t2hVdfROHw9MVxGfrQDBfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T06:48:26Z"
    mac: ENC[AES256_GCM,data:3q6tiIcOikJ2Upa5bPXNKCOoqkCofK/Pyz0HzWgkzaglowHVJmisXyjrYyQABvVfQ364TxB8QSyJuQyw3UtkZ262nadLi+BwvTzg90VlZmbUJrJ8fGjnsT7HNe47/gbDNvb7zoWLtUxUQTj6lZqQzYGCEhGA74MyHul8j4RYYes=,iv:Q01WNjUjRAJoGxg8C6LLPjfX+5Kbxi74SFLYiupWc+U=,tag:Dv6n5TiuWHaNTdhedO+SoQ==,type:str]
    version: 3.13.3
