apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao
spec:
  provider:
    vault:
      server: https://openbao.openbao.svc:8200
      path: kv
      version: v2
      # base64 of ../ca.crt, the offline OpenBao CA. Replace both together.
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ4VENDQVd5Z0F3SUJBZ0lVWWtUb3NoQ2QxNjc2VUNIRTQ0WW93dnJFRVk0d0NnWUlLb1pJemowRUF3SXcKTHpFUU1BNEdBMVVFQ2d3SGFHOXRaV3hoWWpFYk1Ca0dBMVVFQXd3U1NHOXRaV3hoWWlCUGNHVnVRbUZ2SUVOQgpNQjRYRFRJMk1UQXdOekl4TkRRME4xb1hEVE0yTVRBd05ESXhORFEwTjFvd0x6RVFNQTRHQTFVRUNnd0hhRzl0ClpXeGhZakViTUJrR0ExVUVBd3dTU0c5dFpXeGhZaUJQY0dWdVFtRnZJRU5CTUZrd0V3WUhLb1pJemowQ0FRWUkKS29aSXpqMERBUWNEUWdBRUtNbGV0RWx4eERzdVBpMWpaTEFvMXhDQUMzQW9wUkg5a3NqVHpXdTVzRFFWdnZNNQpSRktzOGcxclVtbnlNZmEyRTBRd3hzZHBzVEM4WklJeGhuSXpaNk5tTUdRd0h3WURWUjBqQkJnd0ZvQVU1RWlvCmFIQXFkK3BrMjQvYXdhMWxzVHNLTmtrd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFEQU9CZ05WSFE4QkFmOEUKQkFNQ0FRWXdIUVlEVlIwT0JCWUVGT1JJcUdod0tuZnFaTnVQMnNHdFpiRTdDalpKTUFvR0NDcUdTTTQ5QkFNQwpBMGNBTUVRQ0lIWFpuT2UxNTBvNU5pUGtOcUttNkoyaU5yWXpKRjdtM2w4eEJ6N204ckZSQWlCTW83KzE3blA5CjltaXpZYU14Z2JCSDdGT3Z0WHg3NktGc24vTmkxZkVwcXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso
          serviceAccountRef:
            name: openbao-eso
