apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - guardrails.yaml
  - network.yaml
  - rbac.yaml
  - policies/workloads.yaml
  - policies/services-pvcs.yaml
  - policies/pods.yaml
  - vcluster/release.yaml
  - addons
  - virtual-sync.yaml
