apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - databases/
  - renovate/
  - keycloak/
  - cloudflare/
  - arc-runner-set/
  - nexus/
  - etcd-backup/
  - garage-gateway/
  - radar/
  - ai-gateway/
