# hosts/node-a.nix — ONSITE storage node (zone onsite). doc 09 §3, doc 10 P1.
#
# Storage role: imports disko-storage (encrypted ZFS pool) + zfs-sanoid (the
# moat) + garage(storage) + tailscale. NOT a proxy node (onsite, fast writes).
{ ... }:
{
  imports = [
    ./disko-storage.nix
    ../modules/zfs-sanoid.nix
    # hardware-configuration.nix is generated by nixos-anywhere at install
    # (--generate-hardware-config). TODO operator: import it once generated:
    # ./node-a-hardware.nix
  ];

  networking.hostName = "node-a";
  # ZFS requires a unique 8-hex-digit hostId. TODO operator: set a real one
  # (e.g. `head -c4 /dev/urandom | od -A none -t x4`).
  networking.hostId = "deadbeef";

  fleet = {
    role = "storage";
    zone = "onsite";
    proxyNode = false;
    # TODO operator: node-A's tailscale0 overlay IP (100.x.x.A), captured in
    # doc 10 Phase 0 addressing. Garage binds all listeners to this.
    tailscaleIp = "100.64.0.10";
  };

  # Per-node Tailscale auth key file (see modules/sops.nix + secrets/.example).
  sops.secrets."tailscale-authkey".sopsFile = ../secrets/node-a-tailscale.sops.yaml;

  # Garage capacity for this node's layout assignment is applied imperatively:
  #   garage layout assign <id-A> -z onsite -c <bytes>   (doc 10 Phase 1)
  # TODO operator: size to the full backup set + retention headroom (factor-3
  # full mirror means usable ~= one node's data disk, doc 09 §11).
}
