apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_CF_ACCOUNT_ID: ENC[AES256_GCM,data:Gi6jVkSFj/J/Ih/X24AQb3e6dYIkZOOYG9Rtz/QF3UM=,iv:UaVr0jWGwPNmAQckmCN7V2ZqF7KorYw/Fhry3+BXP8c=,tag:LZ+8mpQOskoFNTwlCdlxXg==,type:str]
    HOMEPAGE_VAR_CF_TUNNEL_ID: ENC[AES256_GCM,data:ZqaWOWcS4GH1HGuhQwyaF5ShOiqiW7M0nK3lHastB9o6TWBb,iv:jMAuMIjh2Ur4jsoSTiO4wDaeAko+VpFxLAtnlFWpA0c=,tag:F+8lGpgpLbtIzIUHt3eXiA==,type:str]
    HOMEPAGE_VAR_CF_API_TOKEN: ENC[AES256_GCM,data:h8xZgOeJ71j0sw==,iv:nIO0bFV2rbLp0lsIA6Wm1ugtZRDhcSJ0rUgxPL+Rc6E=,tag:4wcDwxvHgMABqZ3luUCVIA==,type:str]
    HOMEPAGE_VAR_TAILSCALE_API_KEY: ENC[AES256_GCM,data:dOuTw7enCY84RQ==,iv:Mmahp51I54yTQjQDuaplf5GcqilNnIX7QuHBtcQ36ao=,tag:XFV5G2nc1/CYOsOAxRgKYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNyszV3dZenRmYzdQWEw3
            M09WL1JUQ2FuOHRReENCbDd1dHhBalc5R2lvCjdwYWlacC9GVUI4MnIzb2I2RG11
            bnZKVjF1WmxYSjhuZDBvZW9EUlBXbUUKLS0tIHk3S1lOTGJKZzd5WXRIb3F5MG43
            ZmRzRGNvY2J1elR4M1N2Qlg3czlXV1UKUWNnOvCECt4amPNdSvhNmOJ5FNZWps66
            2xViQzI3b1f4FF4TSkUSlbKlrs+FUIgCitxUOlLfpWrM/kuCYTTJpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T22:53:12Z"
    mac: ENC[AES256_GCM,data:Xpy6zKuCRDC4QZ52BbGIOBBPluadicqrcJzTJ5zisKVLBXeZtsYgFJuSM8q4UIAC/Spf1j7cAlGDthPlpgOkxuXtIjS8VoGtiuoDcJtEqBME5fpjU8iph+yq4ZtWX+lq8uuzfjwtmC5b4SDMilkxT5FnYz30nh34QWsFzKJEx5c=,iv:iak5ZID3xOX89RPLwyn07PXFZxorMFY+C3h8H513Mwg=,tag:f7FJhuhgAo8lUDflGQd+8g==,type:str]
    version: 3.13.3
