apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - satellite-talos.yaml
  - satellite-pools.yaml
  - storageclass-ssd.yaml
  - storageclass-ssd-single.yaml
  - linstor-passphrase.enc.yaml
  - ingress-tailscale.yaml
