apiVersion: v1
kind: Secret
metadata:
    name: linstor-passphrase
    namespace: piraeus-datastore
type: Opaque
stringData:
    MASTER_PASSPHRASE: ENC[AES256_GCM,data:FOGGRe2U90jPkWl2dQhQNTarO6vUhL2Vb0MYCLK8jiUHG17UCmy6MXCBfQ==,iv:3nI32aJ9mXVbGmvurdIAi4Bp1WgFArE+AsSzW3KQkc0=,tag:wJK4V6jeTdamYd6MMXvpWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLN1RaUVZkTVczMVJXb0xD
            WXJ0b3JNRjF0MTNUK2RmNEFTUDlrWUZSOEFVCnBDN2dVUHlaeFNNajJiMzNtc08y
            dzMzYWY0azQ4RXpoMzdLTFRNZnVxYncKLS0tIEZZYTdMTlZEcUpzakxmRDRJZGVa
            NDFIWmFZeGRCTGY0WHFiUDN5aHEvRzgKfL1iQ9a6Ppsx+p1vetMQbsu8nAe8VwWF
            x8u63q4Bn6VUgUEPJEhETrEhdL/i9w9I4dliz5fj5LBXJV/FQvzZVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T15:51:16Z"
    mac: ENC[AES256_GCM,data:fUKEOph6USN/NeHFd8Be1xrN2Tt1ZKBI3NvqPf4DkJajTWCCfUBmnTif595mey80EQP+Trxi6XFzKPlsjHH/JRi+PKWeH6y87NXZTrIG9pwzDUr50GVvL23xMDldY6PINrt6ejhsXasWuwoiNYQ8bUn0h9YbS0F0ukxZ185XPic=,iv:OkiBOo61OeI5T3ALdAXARKlzCjuaDeIu2LqB6CMOzAA=,tag:oFxILLF3t9C8G+IlDHY0Vw==,type:str]
    version: 3.13.3
