apiVersion: v1
kind: ServiceAccount
metadata:
  name: preview-driver
  namespace: dev-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: preview-reader
  namespace: dev-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: preview-reaper
  namespace: dev-platform
