apiVersion: v1
kind: Secret
metadata:
    name: zot-secrets
    namespace: registry
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:KQa/Rom1kZq3q5PcrEg1l8rXbHisTVe+QbEowRsxWo35mXhC7PlJE1lwWiuLAOQSJRlLFT0Pl5Jo/VKtDrAq2w==,iv:kSJo1jFVyM6TSgDaHiDjGokNZFWN1WMNoJzqipNYsDQ=,tag:PQe0lrA9H4KGVMs3JXHLEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcGcyNGVicDdnOG9GNFZ3
            d0dvSmN1OEw1cmNGaG52Nml4b1M0NTdpR3dZCitQYzhVSVlKOWdxbWM5Nm9TcXpL
            U3pJeGJocHNpVVlZb3BTcHBCK3h1QnMKLS0tIDRkdHlhQnVPOEtxVnkvSkNpZXNJ
            QnZlMlRqcTdkL0JxSzRIT0k4Y2lPNDgKs3hDFCv/SyggwiiC2KjQEO/MBvjItb8a
            gQSm7dCqM47a6NFVfagYe5YmgwUUwEIcZEFmdBQFPcbRBA0FQVB0Xg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T11:35:57Z"
    mac: ENC[AES256_GCM,data:2VOR9b5xm01OsxVolJlEU2gCcoBwONqDXKwQZy5EK+uRrV5mpX02mDcTg8LGJcN/EEfsoDlW8fAaMv8smrwAdbpfZDw9K4TzHupwkZ3A7++ZFYBOnUUI4SKfluEu0Iccrh0jZQpixOqQjqoAe8fGkc0RUqSBU3o8vY5GU14x8JY=,iv:bPhhaxYOc7wQG+SXSc5Ye2fMHVkLu+w/7AQfUkM0LjI=,tag:0Y0b9BNqnVQ9F79pQh2BTg==,type:str]
    version: 3.13.3
