apiVersion: v1
kind: Secret
metadata:
    name: zot-ci-credentials
    namespace: registry
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ej0=,iv:u2twl3MtduvcNMmFB4eAdPsZgpDNS5b6iJYxBGNivR0=,tag:ZU5RFp3v9r5P0jRsXI9u0Q==,type:str]
    password: ENC[AES256_GCM,data:dM+ZOtVaSkQ2ZjJScpIcP88KIrRe1zujLQzgozXyiW4WRqNqmSHfp4KsGQ==,iv:U9jhhJF8qIeElqEbbuhUY6FGbSnLCLxqsEw6vbZyd4k=,tag:dT4JFbNfGNRYIL/xSnuvcg==,type:str]
    .dockerconfigjson: ENC[AES256_GCM,data:wbmNb7hVXAK5EAMcQRqAz+dqJwDr3JSzV2mngtmpdlzBGqU6HNXYuUqN+C/m89Ko+znIBJUYnaGOwJiMRkXEIJPCiyB0Hg4txdM2jZ4IYvJX7Mko0gsP4TUPp9xhCx8uv/ZIkEoQLh7IX+BD7nPXt4bwC8cDEw==,iv:YwxLwJbZjsZ+SFEo68tRbPDvB2tzFUdtXnADDL3oKck=,tag:rNCjbAwNgm6dgzuOtPkEXw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4N0RReC9qOWE2TmxTbUJC
            VlJmSERRVTRDUnNySTFkRDBIdjJacDJPaUV3Cnlaek50NXFvc3YxeE9PZGhsVVJW
            NW5vaVRwMmtmN3I0MWlmTTRaU1JsQUEKLS0tIFBaaitrWlZxMXUrVSs0cFFDd1NJ
            cGZXbWtEWFRXd2lxZjBVN1dqTHBnTWsK8fU3Ux39sLtk0fWBra7K+kneJ/NnxhJA
            TXQ1E4D4L8iCmxUUaDIM+b0hDcN6lpKTOiMnMB/KdsmlBD0CizIhMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age137z0k38fp0keu5ns4005e7cv4qlwt320wyf96y48a57sv42k6v9szh5ng3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T11:35:58Z"
    mac: ENC[AES256_GCM,data:sMcTx/qXngnqNGJ3xrNdjl3Qoupp8sFLAaq5si122ELX7DHd4alRHk9bZoGWdFx8DERgugy2G7Kwy/Ev3s87iZY3DEB4gDR6jc6YlV4FxMnQe8tX+fb9WEwambAeXwzI/6dx1jrezMe5tPEqENljr9rwuqA7jDzdT8R4Ws78Z18=,iv:xCi2TQ9YoKDhbdZKfNkKPws4gy1Pe36e978kqJuj3R8=,tag:EdGN27CBl+qY4CN0hEl58Q==,type:str]
    version: 3.13.3
