title: Homelab
theme: dark
color: slate
headerStyle: boxed
statusStyle: dot
layout:
  Observability:
    style: row
    columns: 2
  Platform:
    style: row
    columns: 3
  Storage:
    style: row
    columns: 2
  Garage S3:
    style: row
    columns: 4
  Apps:
    style: row
    columns: 5
  Public apps:
    style: row
    columns: 3
  Cloudflare:
    style: row
    columns: 4
  Tailscale:
    style: row
    columns: 4
  GitHub:
    style: row
    columns: 3
