- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: Homelab_staging
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
