apiVersion: v1
kind: LimitRange
metadata:
  name: memory-defaults
  namespace: seaweedfs
spec:
  limits:
    - type: Container
      defaultRequest:
        memory: 32Mi
      default:
        memory: 256Mi
