apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-alerts
  - flux-am
  - fbref-grafana
  - etcd-backup-alerts
  - cnpg-alerts
  - n8n-metrics
  - node-capacity-alerts
  - control-plane-alerts
  - ingestion-alerts
